#include <iostream>
#include <fstream>
#include <sstream>
#include <chrono>
#include <time.h>

#include <TGraph.h>
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <TRandom3.h>
#include <TTree.h>
//#include <TEveManager.h>
//#include <TEveArrow.h>
//#include <TEveGeoShape.h>

#include "ReadConfiguration.h"
#include "Constants.hpp"
#include "Utilities.hpp"
#include "MrsTau.h"
#include "FileOperations.hpp"
//#include "Display.h"

using namespace IFHB;

int FindNuEnergyLine(std::string fileNameIn, double energy){
	int nLineEnergy = 0;
	bool isFound = false;
	std::vector<double> vFileContent;

	do{
		nLineEnergy = FileOps::FindToken(fileNameIn,"*",nLineEnergy);
		vFileContent = FileOps::RetrieveFileContent(fileNameIn,'h',nLineEnergy+1);
		if(vFileContent[0] == energy){
			isFound = true;
		}
		
		nLineEnergy++;

	}while(!isFound);

	return nLineEnergy;

}


void PrintHelpMessage(){
	std::cout << "** I Stay On Ground **" << std::endl;
	std::cout << std::endl;
	std::cout << "Command Line options: " << std::endl;
	std::cout << "\t -h or --help:\t\t\tThis help message"<<std::endl;
	std::cout << "\t -c or --configfile <Config File>\t\t\tConfiguration file ExACT.cfg"<<std::endl;
	std::cout << "\t -s or --seed <Config File>\t\t\tRandom number generator seed"<<std::endl;
	std::cout << "\t -of or --outputfile\t\t\t File name base for the files generated by IFHB"<<std::endl;
	std::cout << "One can also give all options for the configuration file directly on the command line. In this case the value from the configuration file is overwritten. For example if you want to set the Neutrino energy in GeV you have to give NEUTRINOENERGY 9.5 as an option."<<std::endl;
	std::cout << std::endl;
}

int main (int argc, char** argv){

    auto start = std::chrono::high_resolution_clock::now();

    std::string flag;
    std::string cfgFileName, outputFileBase;
    unsigned int ranSeed = 0; // Default to 0

    ReadConfiguration *readConf;
	
	/////////// Debug Histograms ///////////////

	// TH2 *hSourceLocations;
	// TH1 *hTauEnergies;
	// TH1 *hEmergenceAngles;




	/////////// Command Line Parse /////////////////

	if(argc<3){
		PrintHelpMessage();
		return 0;
	}else{
		for(int i = 1; i<argc; i++){
			flag = argv[i];
			if(i+1>argc){
				std::cout<<"Argument for flag " << argv[i] << " is not present"<<std::endl;
			}else{
				if(flag=="-h" || flag == "--help"){
					PrintHelpMessage();
					return 0;
				}else if(flag=="-c" || flag == "--configfile"){
					cfgFileName = argv[i+1];
					readConf = new ReadConfiguration(cfgFileName);
				}else if(flag=="-of" || flag == "--outputfile"){
					outputFileBase = argv[i+1];
				}else if(flag=="-s" || flag == "--seed"){
					ranSeed = std::stoi(argv[i+1]);
				}
			}
			i++;
		}
	}

	// Overwrites with command-line arguments
	readConf->ReadCommandLine(argc,argv);

	///////////// Output Files ////////////////////
	
	std::string fileNameRoot;
	std::string fileNameSims;
	if(readConf->bIsBelowLimb){
		//IFHB Output for sim control
		fileNameRoot = outputFileBase+"_E_"+std::to_string(readConf->dNeutrinoEnergy)+"_Ze_"+std::to_string(readConf->fPointSourceZe)+"_Az_"+std::to_string(readConf->fPointSourceAz)+".root";
		//IFHB Output for CHASM/GrOptics
		fileNameSims = outputFileBase+"_E_"+std::to_string(readConf->dNeutrinoEnergy)+"_Ze_"+std::to_string(readConf->fPointSourceZe)+"_Az_"+std::to_string(readConf->fPointSourceAz)+".txt"; 
	}else{
		fileNameRoot = outputFileBase+"_E_"+std::to_string(TMath::Log10(readConf->dCosmicRayEnergy))+"_Ze_"+std::to_string(readConf->fPointSourceZe)+"_Az_"+std::to_string(readConf->fPointSourceAz)+".root";
		//IFHB Output for CHASM/GrOptics
		fileNameSims = outputFileBase+"_E_"+std::to_string(TMath::Log10(readConf->dCosmicRayEnergy))+"_Ze_"+std::to_string(readConf->fPointSourceZe)+"_Az_"+std::to_string(readConf->fPointSourceAz)+".txt"; 
	}
	
	TRandom3 *rand = new TRandom3(ranSeed); 

	/////////// Initialize Classes ////////////////
	MrsTau *mrsTau = new MrsTau(readConf);

	mrsTau->SetRandomEngine(rand);
	
	////////////// Data containers for LUTs ////////

	TGraph2D *energyFractionsLUT = new TGraph2D();
	TGraph2D *probExitLUT = new TGraph2D();

	std::vector<double> emergenceAngles = FileOps::RetrieveFileContent(readConf->sFileNameEmergenceAngles,'v',0);
	std::vector<double> energyFractions = FileOps::RetrieveFileContent(readConf->sFileNameEnergyFractions,'v',0);
	std::vector<double> energyNu = FileOps::RetrieveFileContent(readConf->sFileNameNuEnergy,'v',0);
	
	///// Read In Tau energy distribution ///////////
	int nLineEnergy;
	std::vector<double> energyDistPoints;
	std::vector<double> probExitPoints;

	int nEnergiesNuFile = 25;
	std::vector<TGraph2D*> vEnergyFractionsLUT;

	if(!readConf->bIsNuEnergySpectrum){
		nLineEnergy = FindNuEnergyLine(readConf->sFileNameEnergyDistribution,readConf->dNeutrinoEnergy);

		for(int i = 0; i<emergenceAngles.size(); i++){
			energyDistPoints = FileOps::RetrieveFileContent(readConf->sFileNameEnergyDistribution,'h',nLineEnergy+1+i);
			for(int j = 0; j<energyDistPoints.size(); j++){
				energyFractionsLUT->SetPoint(energyFractionsLUT->GetN(),emergenceAngles[i],energyFractions[j],energyDistPoints[j]);
			}

		}

	}else{//Load whole file into memory for quicker access.
		vEnergyFractionsLUT= std::vector<TGraph2D*>(nEnergiesNuFile,new TGraph2D());
		
		for(int i = 0; i < nEnergiesNuFile; i++){
			nLineEnergy = FindNuEnergyLine(readConf->sFileNameEnergyDistribution,6.0+i*0.25);
			energyDistPoints.clear();
			for(int k = 0; k<emergenceAngles.size(); k++){
				energyDistPoints = FileOps::RetrieveFileContent(readConf->sFileNameEnergyDistribution,'h',nLineEnergy+1+k);
				for(int j = 0; j<energyDistPoints.size(); j++){
					vEnergyFractionsLUT[i]->SetPoint(vEnergyFractionsLUT[i]->GetN(),emergenceAngles[k],energyFractions[j],energyDistPoints[j]);
				}

			}
		}

	}

	for(int i = 0; i < energyNu.size(); i++){
		probExitPoints = FileOps::RetrieveFileContent(readConf->sFileNameProbExit,'h',i);
		for(int j = 0; j<probExitPoints.size();j++){
			probExitLUT->SetPoint(probExitLUT->GetN(), emergenceAngles[j],energyNu[i],probExitPoints[j]);
		}
	}		

	//////////////////////// Text Output File ////////////////////////////////
	bool debug = true; // changed to true so we can extract the decay length 
	std::ofstream fIFHBOutText(fileNameSims.c_str());
	fIFHBOutText<< "The First 11 Arguments are for CHASM and the last 5 for GrOptics. Please Skip this line when parsing "<< std::endl;
	fIFHBOutText<< "CHASM: PolarAngle(rad) AzimuthAngle(rad) XTel(m) YTel(m) ZTel(m) Telescope Radius(m) XMax(g/cm^-2) NMax(N particles) X0(g/cm^-2) Lambda Neutrino Energy(GeV)";
	if(debug){
		fIFHBOutText<< " Tau energy(GeV) Decay length(m) ShowerStartX(m) ShowerStartY(m) ShowerStartZ(m)";
	}
	fIFHBOutText<<"(Skip this line)"<<std::endl;

	//double directViewAngle;
	//double elevEmergenceAngle, phiEmergenceAngle, alphaAngle;

	std::vector<double> energyProbability;

	std::cout<<std::endl;

	for(int i = 0; i < readConf->iNShowers; i++){
		double showerEM = TMath::DegToRad()*rand->Uniform(0,15); //shower emergence angle in coordinate system of telescope, 1-5 deg
		double showerZN = TMath::Pi()/2 - showerEM; //shower zenith in coordinate system of telescope, 85-89 deg
		double showerAZ = TMath::DegToRad()*rand->Uniform(0,15); //shower azimuth, 0 deg
		//double showerAZ = TMath::ACos(rand->Uniform(TMath::Cos(TMath::DegToRad() * 15.0), TMath::Cos(TMath::DegToRad() * 0.0))); //shower azimuth, 0 deg
		if(rand->Uniform(1)>=0.5){showerAZ = 2*TMath::Pi() - showerAZ;} //randomly make azimuth negative
		double ppYdim = Constant::REarth*1000*(1-TMath::Sin(showerZN)); //y dimension of plane parallel to showerZN
		double ppXdim = 2*ppYdim*TMath::Tan(TMath::DegToRad()*readConf->fCameraAngularWidth); //x dimension of plane parallel to showerZN with width defined by fCameraAngularWidth
		//generate random point on triangular plane perpendicular to showerZN
		double rn1 = rand->Uniform(1);
		double rn2 = rand->Uniform(1);
		double rtX,rtY;
		if(rn1+rn2<=1){
			rtX = ppXdim/2*(rn1-rn2);
			rtY = ppYdim*(rn1+rn2);
		}
		else{
			rtX = ppXdim/2*(rn2-rn1);
			rtY = ppYdim*(2-rn1-rn2);
		}
		//project points from triangular plane onto sphere/Earth
		double alpha = rtY*TMath::Sin(showerZN);
		double dumAng = TMath::Pi() - TMath::ASin((Constant::REarth*1000+alpha)*TMath::Sin(showerZN)/(Constant::REarth*1000));
		double eTheta = TMath::Pi() - dumAng - showerZN;
		double ePhi = TMath::ATan(rtX/rtY);
		std::vector<double> ePos = {Constant::REarth*1000*TMath::Sin(eTheta)*TMath::Cos(ePhi),
			Constant::REarth*1000*TMath::Sin(eTheta)*TMath::Sin(ePhi),
			Constant::REarth*1000*TMath::Cos(eTheta)}; //position of tau emergence in coordinate system centered on Earth
		//get telescope position relative to the shower emergence points.
    	//rotate by pi about z axis s.t. telescope is in front of shower rather than behind
		/*vector<double> simPos = {-1*(0-ePos[0]),
			-1*(0-ePos[1]),
			Constant::REarth*1000+readConf->fTelAltitude-ePos[2]};*/
		std::vector<double> simPos = {ePos[0],
			ePos[1],
			Constant::REarth*1000+readConf->fTelAltitude-ePos[2]}; //position of telescope for CHASM coordinates (relative to shower emergence point)
		double chasmZN = showerZN + eTheta;

		for(int j = 0; j<energyFractions.size(); j++){
			energyProbability.push_back(energyFractionsLUT->Interpolate(TMath::Pi()/2 - chasmZN,energyFractions[j]));
		}

		//generate a neutrino energy on a power law (-2) distribution
		double rn3 = rand->Uniform(1);
		double eNu0 = std::pow(10.0,readConf->dNeutrinoEnergy);
		double eNu1 = std::pow(10.0,readConf->dNeutrinoEnergy+4);
		double eNu = std::pow((std::pow(eNu1,-1) - std::pow(eNu0,-1))*rn3 + std::pow(eNu0,-1),-1);
		mrsTau->SetNeutrinoEnergy(eNu);

		mrsTau->SetTauEnergyDistributionInverse(energyFractions,energyProbability);
		mrsTau->RunSimulation(chasmZN);

		// Calculate shower start position in CHASM coordinates
		double decayLength = mrsTau->GetDecayLength(); // Get decay length from tau simulation
		
		// Tau flight direction (unit vector) in CHASM coordinates
		double tau_dir_x = TMath::Sin(chasmZN) * TMath::Cos(showerAZ);
		double tau_dir_y = TMath::Sin(chasmZN) * TMath::Sin(showerAZ);
		double tau_dir_z = TMath::Cos(chasmZN);
		
		// Shower start position in CHASM coordinates (relative to emergence point)
		double shower_start_x = tau_dir_x * decayLength;
		double shower_start_y = tau_dir_y * decayLength;
		double shower_start_z = tau_dir_z * decayLength;
		
		if(true){
			std::cout << "Shower start position (CHASM coords): x=" << shower_start_x 
			          << " y=" << shower_start_y << " z=" << shower_start_z << " m" << std::endl;
		}

		fIFHBOutText<<chasmZN<<" ";
		fIFHBOutText<<showerAZ<<" ";
		fIFHBOutText<<simPos[0]<<" ";
		fIFHBOutText<<simPos[1]<<" ";
		fIFHBOutText<<simPos[2]<<" ";
		fIFHBOutText<<readConf->fTelCollectionSphere<<" ";
		fIFHBOutText<<mrsTau->GetXMax()<<" ";
		fIFHBOutText<<mrsTau->GetNMax()<<" ";
		fIFHBOutText<<mrsTau->GetX0()<<" ";
		fIFHBOutText<<mrsTau->GetLambda()<<" ";
		fIFHBOutText<<mrsTau->GetNeutrinoEnergy();
		if(debug){
			fIFHBOutText<<" "<<mrsTau->GetTauEnergy()<<" ";
			fIFHBOutText<<mrsTau->GetDecayLength()<<" ";
			fIFHBOutText<<shower_start_x<<" ";
			fIFHBOutText<<shower_start_y<<" ";
			fIFHBOutText<<shower_start_z;
		}
		fIFHBOutText<<std::endl;
	}

	/*for(int i = 0; i < 3; i++){
		double telX = (i+1)*50000; //in m
		double telY = 0;
		double telZ = 3000;
		double tanElev = telZ/telX;
		elevEmergenceAngle = TMath::ATan(tanElev); //in rad
		phiEmergenceAngle = 0;
		for(int j = 0; j<energyFractions.size(); j++){
			energyProbability.push_back(energyFractionsLUT->Interpolate(elevEmergenceAngle,energyFractions[j]));
		}

		mrsTau->SetTauEnergyDistributionInverse(energyFractions,energyProbability);
		mrsTau->RunSimulation(elevEmergenceAngle);

		fIFHBOutText<<"\t\t";
		fIFHBOutText<<90-(elevEmergenceAngle*180/TMath::Pi())<<"\t";
		fIFHBOutText<<(phiEmergenceAngle*180/TMath::Pi())<<"\t";
		fIFHBOutText<<telX<<"\t";
		fIFHBOutText<<telY<<"\t";
		fIFHBOutText<<telZ<<"\t";
		fIFHBOutText<<mrsTau->GetXMax()<<"\t";
		fIFHBOutText<<mrsTau->GetNMax()<<"\t";
		fIFHBOutText<<mrsTau->GetX0()<<"\t";
		fIFHBOutText<<mrsTau->GetLambda()<<"\t";
		fIFHBOutText<<mrsTau->GetNeutrinoEnergy()<<"\t";
		fIFHBOutText<<mrsTau->GetTauEnergy()<<"\t";
		fIFHBOutText<<mrsTau->GetDecayLength();
		fIFHBOutText<<std::endl;
	}*/

	/////////// Close output files //////////////
	fIFHBOutText.close();

	////////// Log Time of execution ////////////
	auto stop = std::chrono::high_resolution_clock::now();
	auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(stop-start).count();
	duration *= 1e-3;

	std::cout<<"Time Elapsed: "<<duration<<" seconds"<<std::endl;

	std::cout<<"**************************************************"<<std::endl;
	std::cout<<"IFHB output files generated at: "<<fileNameSims<<std::endl;
	std::cout<<"IFHB Diagnostic output file generated at: "<<fileNameRoot<<std::endl;
	
	std::cout<<"\n Simulations Finished.  Have a * nice * day \n"<<std::endl;

	
	return 0;
}
