#ifndef F_MRSTAU_H
#define F_MRSTAU_H

#include <iostream>
#include <fstream>

#include <TF1.h>
#include <TGraph.h>
#include <TGraph2D.h>
#include <TMath.h>
#include <TRandom3.h>
#include <Math/Polynomial.h>
#include "ReadConfiguration.h"
#include "Constants.hpp"
#include "Utilities.hpp"


namespace IFHB{
	/**
	 * \class MrsTau
	 * \brief Container class for loading the exit probabilities and other parameters related to the shower to simulate
	 * 
	 * This class will load the exit probabilities from the nutau P(exit) file generated by NuTauProp.
	 * The file has been converted to csv and is contained in the ./data folder.
	 * The main file contains the probability of exit arranged in columns and rows. The additional files contain information about the angle it corresponds to and the energy of the tau neutrino.
	 * 
	 * I have named this class in honor of Mrs. Tau my 10 y.o. dog.
	 * */
	class MrsTau{
	public:

		

		/**
		 * Standard constructor with no parameters
		 * 
		 * */
		MrsTau();
		/**
		 * Constructor with input files from ReadConfiguration
		 * 
		 * Converts neutrino energy from config file to GeV.
		 * 
		 * @param readConf configuration file loaded into memory
		 * */
		MrsTau(ReadConfiguration *readConf);
		/**
		 * Standard destructor with no parameters
		 * 
		 * */
		~MrsTau();
		/**
		 * Loads the emergence probabilities from file and stores them in a TGraph2D. This in order to obtain the exit probabilities at different emergence angles and energies, using the ROOT TGraph2D interpolation method (Delunay)
		 * 
		 * @param fileNameProb string with the file name with the exit probability table values.
		 * @param fileNameEmergence string with the file name for the emergence angles (column labels)
		 * @param fileNameEnergy string with the file name for the neutrino energies (row labels)
		 * 
		 * */
		void LoadPExitFromFile(std::string fileNameProb, std::string fileNameEmergence, std::string fileNameEnergy);

		/**
		 * Retrieves the exit probability for the Tau
		 * 
		 * @param angle A double with the emergence angle of the Tau (same as neutrino)
		 * @param energy A double with the energy of the incoming neutrino
		 * 
		 * return A double with the exit probability 
		 * */
		double GetExitProbability(double angle, double energy);

		/**
		 * 
		 * Writes CHASM input file
		 * 
		 * */

		std::string PrintCHASMEvent();


		/**
		 * Loads the energy distribution for an emerging Tau based on the nuSpaceSim etau fractions.
		 * 
		 * @param fileNameE A string wih the file name containing the energy distributions
		 * The file is prepared using the HD5 file from nuSpaceSim. It contains a collection of objects that contain 
		 
		 * */
		void LoadECDFFromFile(std::string fileNameE);

		/**
		 * Calculates lambda from the shower Width.
		 * 
		 * return lambda GH parameter
		 * */

		double CalculateLambda();

		/**
		 * Sets Neutrino energy
		 * 
		 * @param energyNu Neutrino energy in GeV
		 * 
		 * */
		void SetNeutrinoEnergy(double energyNu);


		/**
		 * Gets Neutrino energy
		 * 
		 * return neutrino energy in GeV
		 * */

		double GetNeutrinoEnergy();

		/**
		 * Loads the energy distribution for an emerging Tau based on the nuSpaceSim etau fractions.
		 * 
		 * @param energyFraction a vector with the energy fraction
		 * @param prob a vector with the CDF of the energy fractions
		 * 
		 * The populated TGraph is the inverted CDF, in order to be able to use a uniform ditribution to sample from it following the inversion method.
		 * 	 
		 * */
		
		void SetTauEnergyDistributionInverse(std::vector<double> energyFraction, std::vector<double> prob);

		/**
		 * 
		 * User defined TF1 template for relativistic particle decay
		 * 
		 * return probability of decay at path lenght l
		 * */

		static double DecayLengthFunction(double *x, double *par);

		/**
		 * 
		 * User definded TF1 to obtain the energy transferred from the neutrino to the tau using the TGraph created from the file describing the CDF
		 * 
		 * return a random sample in the energy fraction distribution
		 * */

		

		void SetTauEnergy(double energyTau);

		/**
		 * 
		 * Sets Random Number generator
		 * @param rand a TRandom3 object with the initialized random number generator
		 * 
		 * */

		void SetRandomEngine(TRandom3 *rand);

		/**
		 * 
		 * Runs the simulation of the parameters. 
		 * Randomly obtains the distance before the decay of the Tau by sampling from the exponential function describing the particle.
		 * 
		 * From the LUT it finds the shower properties for a shower carrying 0.5 of the energy of the Tau.
		 * 
		 * Since the desired parameter is lambda, and the LUTs are for the shower width, the equation describing the width from lambda, can be transformed to a depressed cubic (square term = 0) in terms of sqrt(lambda). Since all of the coefficients are real and positive, the discriminant is negative, therefore there is only one real root which is related to lambda.
		 * 
		 * @param Emergence angle of the tau
		 * 
		 * */
		void RunSimulation(double angleEmergence);

		/**
		 * 
		 * Sample from energy spectrum for cosmic Rays. In case a fixed energy for the shower is not desired, it randomly samples from a -2 index profile
		 * Range of sampling is from 10^6 to 10^12 GeV
		 * 
		 * return log(E[GeV]) of Neutrino rounded to nearest quarter decade (6.0, 6.25, 6.50...)
		 * */
		double SampleNeutrinoSpectrum(double eStart=1e6, double eEnd=1e12);

		/**
		 * 
		 * GetTauEnergy
		 * 
		 * return a double with the energy of the Tau
		 * */

		double GetTauEnergy();

		/**
		 * 
		 * Get decay length
		 * 
		 * return a double with the decay length
		 * 
		 * */

		double GetDecayLength();

		/**
		 * 
		 * Get GH Xmax
		 * 
		 * */

		double GetXMax();

		/**
		 * 
		 * Get GH NMax
		 * 
		 * */

		double GetNMax();

		/**
		 * 
		 * Get GH X0
		 * 
		 * */

		double GetX0();

		/**
		 * 
		 * Get GH Lambda
		 * 
		 * */

		double GetLambda();



	private:
		TGraph2D *probExitSurface;/**<Probability distribution P(beta, E)*/
		
		TGraph *probEnergyDistribution;/**< Energy Fraction distribution for the exiting Tau from specific neutrino energy P(eTau/Enu)*/
		TGraph *showerNMax;/**< TGraph containing the Number of charged particles in a shower with the energy of the tau that initiates it*/
		TGraph *showerXMax;/**< TGraph containing the XMax in a shower with the energy of the tau that initiates it*/
		TGraph *showerWidth;/**< TGraph containing the Width of the shower with the energy of the tau that initiates it*/

		TF1 *decayLengthFunction;
		TF1 *energyFractionFunction;

		double probExit;/**< Probability that the Tau exits*/
		double probDecay;/**<Probability that the Tau decays in the atmosphere*/
		double eNu;/**< Energy of the original neutrino*/
		double eTau;/**< energy of the Tau exiting*/

		//Gaisser-Hillas Parameters
		double eShower;/**<energy of the shower*/
		double nMax;/**< Number of charged particles in shower*/
		double xMax;/**< X_Max in GH*/
		double lambda;/**< Related to shower width*/
		double x0;/**< X0 in GH*/

		double decayLength;/**< Decay length of Tau*/

		double bsmFactor;/**< Factor to scale lifetime of Tau for BSM effects*/

		TRandom3 *rand;/**< Random number generator engine*/


	};
}
#endif